### PR TITLE
changed base url to https

### LINKED ISSUE #2: css/js linked resources are not loaded properly
css/js linked resources are not loaded properly because main page is loaded via https and the rest is trying to load via http only:

```
Mixed Content: The page at 'https://blog.dkraic.com/' was loaded over HTTPS, but requested an insecure stylesheet 'http://blog.dkraic.com/css/slim.css'. This request has been blocked; the content must be served over HTTPS.
blog.dkraic.com/:11 Mixed Content: The page at 'https://blog.dkraic.com/' was loaded over HTTPS, but requested an insecure stylesheet 'http://blog.dkraic.com/css/highlight.min.css'. This request has been blocked; the content must be served over HTTPS.
```

### PR DESCRIPTION
**Pull request by s4muel**
should close #2

### CODE REVIEW

**Comment by matusk** [comment]
@s4muel :+1:

**Comment by danielkraic** [comment]
`lynx --dump dev.dkraic.com`

**Comment by danielkraic** [comment]
`$ notify-send "$(curl -s https://dev.dkraic.com | grep h1 | grep -o ">.*<" | tr -d "><")"`

**Comment by s4muel** [comment]
should i close this one?

**Pull request merged**
